orbs:
  heroku: circleci/heroku@1.2.4
version: 2.1
jobs:
  auth:
    executor: heroku/default
    steps:
      - heroku/install
      - setup_remote_docker:
          version: 19.03.13
workflows:
  heroku_deploy:
    jobs:
      - auth
      - heroku/push-docker-image