orbs:
  heroku: circleci/heroku@1.2.4
version: 2.1
jobs:
  build:
    executor: heroku/default
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image
workflows:
  heroku_deploy:
    jobs:
      - build